### ISSUE TITLE
Unsatisfied link error

### ISSUE THREAD

**Issue by dtr5** [krenfro/fannj#8]
Using JNA 3.1.0 and openjdk version "1.8.0_91", the following code

```
import com.googlecode.fannj.Fann;

public class main {

    public static void main(String[] args) {
        Fann ann = new Fann("xor.net");
        System.out.println(ann.run(new float[]{0.0f, 0.0f}));
        System.out.println(ann.run(new float[]{0.0f, 1.0f}));
        System.out.println(ann.run(new float[]{1.0f, 0.0f}));
        System.out.println(ann.run(new float[]{1.0f, 1.0f}));
    }

}
```

throws

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.googlecode.fannj.Fann.fann_create_from_file(Ljava/lang/String;)Lcom/sun/jna/Pointer;
    at com.googlecode.fannj.Fann.fann_create_from_file(Native Method)
    at com.googlecode.fannj.Fann.<init>(Fann.java:74)
    at main.main(main.java:7)
```

The library includes the symbol

```
nm -g /usr/local/lib/libfann.so | grep "fann_create_from_file" 
0000000000009b40 T fann_create_from_file
```

Edit: minor typo: libfann, the library actually being loaded, also has fann_create_from_file

**Comment by krenfro** [comment]
Are you setting LD_LIBRARY_PATH and jna.library.path?

**Comment by dtr5** [comment]
I'm using java -Djna.library.path=... . LD_LIBRARY_PATH is empty.

I reimplemented that part of the library using the other JNA access method

```
public interface FannLibrary extends Library {
        FannLibrary INSTANCE = (FannLibrary) Native.loadLibrary("libfann", FannLibrary.class);

        Pointer fann_create_standard_array(int numLayers, int[] layers);
...
```

and it works fine. But I haven't tested if this approach works in windows.
